services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src/chatbot-ui:/app/src/chatbot-ui
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

